// ======================================================
// App / Core / Constants
// ======================================================

export const APP_STATE = {
  LOGIN__ADDING_USERNAME_VALIDATION: "LOGIN__ADDING_USERNAME_VALIDATION",
  LOGIN__ADDING_PASSWORD_VALIDATION: "LOGIN__ADDING_PASSWORD_VALIDATION",
  HEADER__UPDATING_USER_INFOS: "HEADER__ADDING_USER_INFOS",
  MOVIES__ADDING_SEARCH_FEATURE: "MOVIES__ADDING_SEARCH_FEATURE",
  MOVIES__ADDING_ORDER_FILTER_FEATURE: "MOVIES__ADDING_ORDER_FILTER_FEATURE",
  MOVIES__ADDING_GENRE_FILTER_FEATURE: "MOVIES__ADDING_GENRE_FILTER_FEATURE",
  MOVIES__DISPLAYING_MOVIE_DATA: "MOVIES__DISPLAYING_MOVIE_DATA"
};

export const OVERLAY_SPEED = 1500;
